"use client"
import { StrictMode } from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  // title: 'Create Next App',
  description: 'Generated by create next app',
  title: '11111',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html>
      <body className={`min-h-screen ${inter.className}`} >
        <Header />
        <div className="px-3 py-6">
          {children}
        </div>
      </body>
    </html>
  )
}
